#!/usr/bin/env bash
#  A script that configures an Nginx server to listen on port 80

#  first remove the default Nginx file
rm /etc/nginx/sites-enabled/default
#  then configure nginx to listen on port 80
ln -sf /etc/nginx/sites-availiable/default /etc/nginx/sites-enabled/default
#  then restart nginx
service nginx restart
