#!/usr/bin/env bash
# script that configures an Nginx server to listen on port 80 and return HTTP 200

# First remove the default Nginx file
sudo rm /etc/nginx/sites-enabled/default

# Create or update the Nginx configuration file to return HTTP 200 status code
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    server_name _;
    return 200;
}
EOF'

# Create a symbolic link to enable the Nginx configuration
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
