#!/usr/bin/env bash
# ^ Shebang line specifying the interpreter to be used

pgrep bash -l
# ^ Use pgrep to search for processes containing the word "bash" in their names
#   -l: List the process name in addition to the PID
