#!/usr/bin/env bash
# ^ Shebang line specifying the interpreter to be used

while true
do
  # Start of the infinite loop
  echo "To infinity and beyond"  # Print the message to the console
  sleep 2  # Pause execution for 2 seconds
done
# End of the loop
