#!/usr/bin/env bash
#Loops from 1 to 10 and displays:
#	"bad luck" for the 4th iteration
#	"good luck" for the 8th iteration
#	"Best School" for all the other itrations

count = 0

while [ "$i" -lt 11 ]; do

  # if 4 bad luck elif 8 good luck
  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((i++))
done
